### ISSUE TITLE
Inference is time-consuming

### ISSUE THREAD

**Issue by zhongcl-thu** [qq456cvb/UKPGAN#5]
Though the sdv_cache is cached, the inference of the pre-trained model is very slow. Does the model run on CPU? I test it on a 3090/2080Ti GPU.

**Comment by qq456cvb** [comment]
This is somewhat expected, as full 3D convolution is involved (more details of sdv at https://github.com/zgojcic/3DSmoothNet). Generally it takes around 1 second for a model. To speed up, you may downsample the points, or replace the sdv feature by some easy-to-compute descriptors (e.g., SHOT, ISS, etc.). Since our pipeline is general, and independent of the choice of rotation-invariant descriptors, the performance should be on par with sdv.

**Comment by qq456cvb** [comment]
Hi, just a reminder, you can try our new Pytorch version with SHOT descriptor integrated, and it is much faster than the original SmoothNet descriptors.

**Comment by zhongcl-thu** [comment]
Great! Would you like to provide a README for Pytorch version? I want to train the model on my own dataset.

**Comment by qq456cvb** [comment]
We now provide a simple readme for building and training with pytorch version.
